name:       flang
version:    0.0.0.0
author:     "Daniel Maier"
maintainer: "maier.dan@campus.lmu.de"

description: Please see README.md

dependencies:
- base
- parsec
- transformers
- containers
- vector
- lens
- extra
- ilist

library:
 source-dirs: lib

ghc-options:
- -Wall

executables:
  flang-tokenize:
    main:        flang-tokenize.hs
    source-dirs: app
    dependencies:
    - flang

  flang-parse:
    main:        flang-parse.hs
    source-dirs: app
    dependencies:
    - flang

  flang-run-vmcode:
    main:        flang-run-vmcode.hs
    source-dirs: app
    dependencies:
    - flang

  flang-run-vmcode-debug:
    main: flang-run-vmcode-debug.hs
    source-dirs: app
    dependencies:
    - flang

  flang-compile:
    main: flang-compile.hs
    source-dirs: app
    dependencies:
    - flang

  flang-run:
    main: flang-run.hs
    source-dirs: app
    dependencies:
    - flang