name:       flang
version:    0.0.0.0
author:     "Daniel Maier"
maintainer: "maier.dan@campus.lmu.de"

description: Please see README.md

dependencies:
- base
- parsec

library:
 source-dirs: lib

ghc-options:
- -Wall

executables:
  flang-tokenize:
    main:        flang-tokenize.hs
    source-dirs: app
    dependencies:
    - flang