name:       flang
version:    1.1.0.0
author:     "Daniel Maier"
maintainer: "maier.dan@campus.lmu.de"

description: Please see README.md

dependencies:
- base
- parsec
- transformers
- containers
- vector
- lens
- extra
- ilist
- hspec

library:
 source-dirs: lib

ghc-options:
- -Wall

executables:
  flang-tokenize:
    main: flang-tokenize.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-tokenize-debug:
    main: flang-tokenize-debug.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-parse:
    main: flang-parse.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-parse-debug:
    main: flang-parse-debug.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-rewrite:
    main: flang-rewrite.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-rewrite-debug:
    main: flang-rewrite-debug.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-typify:
    main: flang-typify.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-typify-debug:
    main: flang-typify-debug.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-compile:
    main: flang-compile.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-compile-debug:
    main: flang-compile-debug.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-run:
    main: flang-run.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-run-debug:
    main: flang-run-debug.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-run-vmcode:
    main: flang-run-vmcode.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

  flang-run-vmcode-debug:
    main: flang-run-vmcode-debug.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang

tests:
  flang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flang
